CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS source.customers (
  source_system TEXT NOT NULL DEFAULT 'optio-demo',
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001),
  name TEXT NOT NULL CHECK (length(btrim(name)) > 0),
  email TEXT NOT NULL CHECK (position('@' IN email) > 1),
  segment TEXT NOT NULL CHECK (length(btrim(segment)) > 0),
  balance NUMERIC(18, 2) NOT NULL DEFAULT 0,
  attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  deleted_at TIMESTAMPTZ,
  PRIMARY KEY (source_system, id),
  CHECK (
    (deleted = FALSE AND deleted_at IS NULL)
    OR (deleted = TRUE AND deleted_at IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS customers_active_keyset_idx
  ON source.customers (source_system, id)
  WHERE deleted = FALSE;

CREATE TABLE IF NOT EXISTS source.outbox_events (
  position BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  schema_version SMALLINT NOT NULL DEFAULT 1 CHECK (schema_version > 0),
  event_id TEXT NOT NULL UNIQUE,
  source_system TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  entity_version BIGINT NOT NULL CHECK (entity_version > 0),
  operation TEXT NOT NULL CHECK (operation IN ('upsert', 'delete')),
  source_timestamp TIMESTAMPTZ NOT NULL,
  canonical_payload JSONB NOT NULL,
  payload_hash CHAR(64) NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
  captured_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (source_system, entity_type, entity_id, entity_version)
);

CREATE INDEX IF NOT EXISTS outbox_events_entity_history_idx
  ON source.outbox_events (source_system, entity_type, entity_id, entity_version);

CREATE OR REPLACE FUNCTION source.customer_event_id(customer source.customers)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
STRICT
AS $$
  SELECT format(
    '%s:customer:%s:%s',
    customer.source_system,
    customer.id,
    customer.version
  );
$$;

CREATE OR REPLACE FUNCTION source.customer_payload(
  customer source.customers,
  event_operation TEXT
)
RETURNS JSONB
LANGUAGE SQL
IMMUTABLE
STRICT
AS $$
  SELECT CASE event_operation
    WHEN 'delete' THEN jsonb_build_object(
      'deleted', TRUE,
      'deletedAt', to_jsonb(customer.deleted_at),
      'entityId', customer.id::text,
      'entityType', 'customer',
      'sourceSystem', customer.source_system,
      'version', customer.version::text
    )
    ELSE jsonb_build_object(
      'attributes', customer.attributes,
      'balance', to_jsonb(customer.balance),
      'createdAt', to_jsonb(customer.created_at),
      'deleted', FALSE,
      'email', customer.email,
      'entityId', customer.id::text,
      'entityType', 'customer',
      'name', customer.name,
      'segment', customer.segment,
      'sourceSystem', customer.source_system,
      'updatedAt', to_jsonb(customer.updated_at),
      'version', customer.version::text
    )
  END;
$$;

CREATE OR REPLACE FUNCTION source.payload_sha256(payload JSONB)
RETURNS CHAR(64)
LANGUAGE SQL
IMMUTABLE
STRICT
AS $$
  SELECT encode(digest(convert_to(payload::text, 'UTF8'), 'sha256'), 'hex')::char(64);
$$;

CREATE OR REPLACE FUNCTION source.prepare_customer_write()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    NEW.version := 1;
    NEW.deleted := FALSE;
    NEW.deleted_at := NULL;
    NEW.created_at := clock_timestamp();
    NEW.updated_at := NEW.created_at;
    RETURN NEW;
  END IF;

  IF OLD.deleted THEN
    RAISE EXCEPTION 'customer %.% is deleted and cannot be changed', OLD.source_system, OLD.id;
  END IF;

  IF NEW.source_system IS DISTINCT FROM OLD.source_system
     OR NEW.id IS DISTINCT FROM OLD.id THEN
    RAISE EXCEPTION 'customer identity is immutable';
  END IF;

  NEW.version := OLD.version + 1;
  NEW.created_at := OLD.created_at;
  NEW.updated_at := clock_timestamp();

  IF NEW.deleted THEN
    NEW.deleted_at := COALESCE(NEW.deleted_at, NEW.updated_at);
  ELSE
    NEW.deleted_at := NULL;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION source.capture_customer_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  event_operation TEXT;
  event_payload JSONB;
BEGIN
  event_operation := CASE WHEN NEW.deleted THEN 'delete' ELSE 'upsert' END;
  event_payload := source.customer_payload(NEW, event_operation);

  INSERT INTO source.outbox_events (
    event_id,
    source_system,
    entity_type,
    entity_id,
    entity_version,
    operation,
    source_timestamp,
    canonical_payload,
    payload_hash
  ) VALUES (
    source.customer_event_id(NEW),
    NEW.source_system,
    'customer',
    NEW.id::text,
    NEW.version,
    event_operation,
    NEW.updated_at,
    event_payload,
    source.payload_sha256(event_payload)
  );

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION source.reject_hard_customer_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'hard delete is disabled; use source.delete_customer(bigint, text)';
END;
$$;

CREATE OR REPLACE FUNCTION source.reject_outbox_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'source outbox events are immutable';
END;
$$;

CREATE OR REPLACE FUNCTION source.delete_customer(
  customer_id BIGINT,
  customer_source_system TEXT DEFAULT 'optio-demo'
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
  affected_rows INTEGER;
BEGIN
  UPDATE source.customers
  SET deleted = TRUE
  WHERE source_system = customer_source_system
    AND id = customer_id
    AND deleted = FALSE;

  GET DIAGNOSTICS affected_rows = ROW_COUNT;
  RETURN affected_rows = 1;
END;
$$;

DROP TRIGGER IF EXISTS customers_prepare_write ON source.customers;
CREATE TRIGGER customers_prepare_write
BEFORE INSERT OR UPDATE ON source.customers
FOR EACH ROW EXECUTE FUNCTION source.prepare_customer_write();

DROP TRIGGER IF EXISTS customers_capture_event ON source.customers;
CREATE TRIGGER customers_capture_event
AFTER INSERT OR UPDATE ON source.customers
FOR EACH ROW EXECUTE FUNCTION source.capture_customer_event();

DROP TRIGGER IF EXISTS customers_reject_hard_delete ON source.customers;
CREATE TRIGGER customers_reject_hard_delete
BEFORE DELETE ON source.customers
FOR EACH ROW EXECUTE FUNCTION source.reject_hard_customer_delete();

DROP TRIGGER IF EXISTS outbox_events_immutable ON source.outbox_events;
CREATE TRIGGER outbox_events_immutable
BEFORE UPDATE OR DELETE ON source.outbox_events
FOR EACH ROW EXECUTE FUNCTION source.reject_outbox_mutation();

CREATE OR REPLACE VIEW source.customer_state_oracle AS
SELECT
  customer.source_system,
  'customer'::text AS entity_type,
  customer.id::text AS entity_id,
  customer.version AS entity_version,
  CASE WHEN customer.deleted THEN 'delete' ELSE 'upsert' END AS operation,
  source.customer_payload(
    customer,
    CASE WHEN customer.deleted THEN 'delete' ELSE 'upsert' END
  ) AS canonical_payload,
  source.payload_sha256(
    source.customer_payload(
      customer,
      CASE WHEN customer.deleted THEN 'delete' ELSE 'upsert' END
    )
  ) AS payload_hash
FROM source.customers AS customer;

CREATE OR REPLACE VIEW source.event_oracle AS
SELECT
  position,
  event_id,
  source_system,
  entity_type,
  entity_id,
  entity_version,
  operation,
  source_timestamp,
  canonical_payload,
  payload_hash,
  captured_at
FROM source.outbox_events;

COMMENT ON TABLE source.customers IS
  'Current customer state, including retained logical-delete tombstones';
COMMENT ON TABLE source.outbox_events IS
  'Immutable canonical source events committed atomically with customer mutations';
COMMENT ON VIEW source.customer_state_oracle IS
  'Source-owned expected current state used for destination reconciliation';
COMMENT ON VIEW source.event_oracle IS
  'Source-owned expected logical event set used for consumer reconciliation';
